### ISSUE TITLE
Pycrc is for C only - right?

### ISSUE THREAD

**Issue by mgiaco** [tpircher-zz/pycrc#12]
Is the other project called pyCRC the python equivalent?

thx
mathias

**Comment by tpircher-zz** [comment]
Hi Mathias,

pycrc is written in Python, and its main purpose is to generate C source code. You can calculate the CRC directly in Python, by importing crc_algoritms, but they are not very optimised.

The other pyCRC -- as far as I know, I haven't tried it -- is a Python module that generates CRCs for a limited number of models. See their website for details. C code is not generated. This project (pycrc.org, github.com/tpircher/pycrc) is not related to the (much younger) namesake on pypi.

What is your aim? Do you want to generate C source or do you want a pure Python implementation to calculate the CRC?

Some projects that are similar to (this) pycrc:
http://crcmod.sourceforge.net/
http://www.nightmare.com/~ryb/
http://www.mcgougan.se/universal_crc/

**Comment by mgiaco** [comment]
Hi, 
I use generated C source from this project on a microcontroller. And for the Host PC I need a pure Python implementation.
So I will try the pyCRC lib.

Thanks
