### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by ThomasWaldmann** [tpircher-zz/pycrc#14]
I'ld be interested in the actual speed of the generated compiled code. Guess quite some other people looking at this project might also be wondering about this.

It would be nice if one could generate a main() function that computes a crc over a specific, given amount of data and measures the time needed for that. Like 1MB of 0x42 or so.

So one could easily compare the different crc algorithms implemented by your code to existing crc implementations to find out what's fastest.

In my case, I am esp. interested in:
- a function fully compatible to python3's zlib.crc32, but (significantly) faster
- any function somehow comparable to crc32, but significantly faster

**Comment by tpircher-zz** [comment]
Is the `performance.sh` script in the `test` directory close to what you are looking for?

**Comment by ThomasWaldmann** [comment]
Ah, cool. Yes, that does the job, thanks for the pointer.

Maybe include that pointer in the README?
