### ISSUE TITLE
Do not get table output

### ISSUE THREAD

**Issue by johannes-lode** [tpircher-zz/pycrc#28]
I do not get any code beside the header comment when I call it as follows
`./pycrc.py --width=8 --poly=0x07 --xor-in=0 --xor-out=0x55 --reflect-in=false --reflect-out=False --table-idx-width=4 --algorithm=table-driven --generate=table`

I ecpected some kind of hex number sequence to be included in my static table (at least v0.7.8 worked this way).

**Comment by tpircher-zz** [comment]
Thanks Johannes for reporting this. This is fixed in v0.9.2

**Comment by johannes-lode** [comment]
Thank you for your really quick response. I will test it the next few days. Regards...
