### ISSUE TITLE
Generation of C file

### ISSUE THREAD

**Issue by Priyanka2092** [tpircher-zz/pycrc#37]
Hi,

I calculated CRC-16/X-25. and Now I want to generate a C-file for that. I am writing the following command.

**pycrc.py --model x-25 --generate c -o crc**

//crc is the file name 
And I am getting the following error:

**pycrc: error: select an algorithm to be used in the generated file**

I am not able to decode this error. Can you please help me with it. Thank you.

**Comment by tpircher-zz** [comment]
Hi Priyanka,

sorry, I must have missed the notification for your request; I reckon this is now late, but the answer is to use the --algorithm=ALGO option. For most applications  --algorithm=table-driven would be a good choice. If the code size or the speed is not good for your application, you can always re-generate the code. Also, see https://pycrc.org/faq.html#best-model for some guidance.
Please reopen this issue if you have any other questions.
