### ISSUE TITLE
"pycrc" != "PyCRC" but same url used in python package index

### ISSUE THREAD

**Issue by Ecordonnier** [tpircher-zz/pycrc#38]
Hello,
I was using PyCRC in my project (https://libraries.io/pypi/PyCRC / https://github.com/alexbutirskiy/PyCRC, which is not maintained any more and has nothing to do with https://github.com/tpircher/pycrc) and my nightly builds started failing, because the python package index removed "PyCRC 1.21" and added "pycrc version 0.9.2" instead (https://pypi.org/project/pycrc/#history shows the release was done on January 24), therefore I started getting those error messages:

```
ERROR: Could not find a version that satisfies the requirement PyCRC==1.21 (from -r requirements.txt (line 3)) (from versions: 0.9.2)
ERROR: No matching distribution found for PyCRC==1.21 (from -r requirements.txt (line 3))
```

I just wanted to document the issue there in case it affects other people. It is quite confusing that the python package index just replaced one package with another even though they are not related, and kept the same package name with a different case, knowing that pip is case insensitive.

**Comment by cantzler** [comment]
We just encountered the same issue as well :(

**Comment by tpircher-zz** [comment]
I am sorry about the problems caused by this. The change on the Python Package Index was initiated by me and agreed with the maintainer of the (other) PyCRC package. It was triggered by the fact that I got contacted by multiple people attempting to install pycrc via pip and who were surprised that they got a different code they were expecting. The joys of a name clash. Sigh.

**Comment by Ecordonnier** [comment]
Hi tpircher! No problem, as far as I understand this change conforms to https://www.python.org/dev/peps/pep-0541/

I don't know how cumbersome it is, but if it is easily doable I would suggest to clarify the situation in the project description at https://pypi.org/project/pycrc/#description
