### ISSUE TITLE
Use "const void*" instead of "const char*" for crc_update()

### ISSUE THREAD

**Issue by KamilSzczygiel** [tpircher-zz/pycrc#4]
When using pycrc with C++ code you need to use a lot of `reinterpret_cast<const unsigned char*>(...)` when calling crc_update() with anything other than `unsigned char`, because C++ doesn't allow implicit conversion between such types. The only implicit conversion that is allowed is "anything" -> "const void*", so I'd propose to change prototype of crc_update() to:

```
crc_t crc_update(crc_t crc, const void *data, size_t data_len);
```

**Comment by tpircher-zz** [comment]
This should be fixed with commit 7052c04ce2.

**Comment by KamilSzczygiel** [comment]
Great, thanks! I'll test that tomorrow in the morning.

**Comment by KamilSzczygiel** [comment]
Thanks again - `reinterpret_cast<...>(...)` is no longer needed.

**Comment by tpircher-zz** [comment]
Thanks Kamil for testing!
