### ISSUE TITLE
Addition to Frequently Asked Questions, Linux-specific : Error ": No such file or directory" when trying to run pycrc.py on Linux

### ISSUE THREAD

**Issue by John-D-Rogers** [tpircher-zz/pycrc#9]
Please consider adding this verbiage to the Frequently Asked Questions list for pycrc : 

Problem : 
Error ": No such file or directory" when trying to run pycrc.py on Linux

Solution : 
After extracting pycrc-0.8.3.zip with the linux 'unzip' command, run the command "dos2unix /path/to/pycrc-0.8.3/pycrc.py" to convert the file from MS-DOS format to Unix format.  

Failure to do this can result in the error ": No such file or directory" when running the command "pycrc.py --help"

Thank you for your attention on this matter.

**Comment by tpircher-zz** [comment]
Thanks John for the feed-back.
I have added this to the FAQ, and also added a second download button on the pycrc.org homepage for a Linux/BSD/OS X file format (tar.gz).

**Comment by John-D-Rogers** [comment]
Thank you for the fast turnaround on this :)

jdr
